version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  php:
    build: ./php
    container_name: "laravel-php"
    tty: true
    volumes:
      - ./src:/var/www/html
    restart: always
  mysql:
    image: mysql
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      #    ports:
      #      - 13306:3306
    expose:
      - 3306
    volumes:
      - ./mysql/default.cnf:/etc/mysql/conf.d/default.cnf
