version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    # 日本時間
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: xn--fkq843ad7f.jp
      #ports:
      #- "8080:80"
      #expose:
      #- 80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  php:
    build: ./php
    container_name: "laravel-php"
    # 日本時間
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    tty: true
    volumes:
      - ./src:/var/www/html
    restart: always
  mysql:
    image: mysql
    container_name: "laravel-mysql"
    # 日本時間
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      #    ports:
      #      - 13306:3306
    expose:
      - 3306
    volumes:
      - ./mysql/default.cnf:/etc/mysql/conf.d/default.cnf
      - ./mysql/mysql_data:/var/lib/mysql
networks:
  default:
    external:
      name: common_link
